spring:
   application:
      name: spring-boot-grpc-demo
      
server:
#   port: 8080
   port: 8443
   http2:
      enabled: true
   ssl:
      key-store-type: PKCS12
      key-store: classpath:localhost.p12
      key-store-password: password
      key-alias: localhost   
grpc:
   port: 8081
   security:
      cert-chain: classpath:localhost.crt
      private-key: classpath:localhost.key
   
management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: ALWAYS